### ISSUE TITLE
Please set the data arg to empty object as default

### ISSUE THREAD

**Issue by pixel-shock** [Veams/plugin-templater#1]
Hi,

I'm running into a problem with templates which don't need any data. For example: Use a template which only loops with a repeat helper from 0 to 200 to generate some stuff ... therefor you don't need any data, because the only "dynamic" stuff within the template is the "repeat" helper.

Maybe I miss some important point on an empty `data` object, but imho not 😉 

```
if (!data && Veams.templater.templates[tplName]) {
	console.error(`VeamsTemplater :: You need to provide some data for ${tplName}.`);
	return;
}
````

to

```
if (!data) data = {};
```

at line https://github.com/Veams/veams-plugin-templater/blob/2688ea42a6e4c39d129dced34dd7ed232a652ed6/src/index.js#L71

**OR** remove it completely and change https://github.com/Veams/veams-plugin-templater/blob/2688ea42a6e4c39d129dced34dd7ed232a652ed6/src/index.js#L81 to

```
return Veams.templater.templates[tplName](data || {});
```

**Comment by Sebastian-Fitzner** [comment]
Default value is now an empty object ...
